baseurl: ""
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: "/post/:title/"
excerpt_separator: <!--more-->
exclude:
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
plugins:
  - jekyll-feed
  - jekyll-redirect-from
permalink: pretty
theme: null
title: "MacPorts"
url: "https://www.macports.org"
